BaseType: !include basetype.raml
DataType: !include datatype.raml
DefaultProperty: !include defaultproperty.raml
EmptyBase: !include emptybase.raml
NoProps: !include noprops.raml
SomeEnum: !include enum.raml
