#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/data-type"
displayName: SupportedRamlTypes

description: >
  Top-level type for defining supported
  [built-in types](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#built-in-types)
  usd to certify **BeanPropertiesSupport**.

properties:
  anyRefTypes:
    type: AnyRefTypes
  anyValTypes:
    type: AnyValTypes
  collectionTypes:
    type: CollectionTypes

