BaseType: !include basetype.raml
DataType: !include datatype.raml
DerivedWithRequired: !include derivedwithrequired.raml
EmptyBase: !include emptybase.raml
NoProps: !include noprops.raml
ParentWithOption: !include parentwithoption.raml
SomeEnum: !include enum.raml
SomeMapType: !include somemaptype.raml