addSbtPlugin("com.github.sbt"   % "sbt-ci-release"     % "1.9.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("com.github.sbt"   % "sbt-github-actions" % "0.24.0")
addSbtPlugin("com.github.sbt"   % "sbt-site-paradox"   % "1.5.0")
addSbtPlugin("com.github.sbt"   % "sbt-ghpages"        % "0.8.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"        % "0.6.4")
