#%RAML 1.0 DataType
(package): DataTypes
# The (docs-uri) custom facet is absent so that "description" can be verified.
displayName: DataType
type: BaseType
(scala-derive-json): true
discriminatorValue: data
description: >
  Sample concrete BaseType.
properties:
  foo?:
    type: string
  customTypeProp:
    (scala-type): "scala.math.BigDecimal"
    type: number
  customArrayTypeProp:
    (scala-array-type): "Vector"
    type: array
    (scala-type): "scala.math.BigDecimal"
    items:
      type: object

