BaseType: !include basetype.raml
DataType: !include datatype.raml
DefaultProperty: !include defaultproperty.raml
DerivedWithRequired: !include derivedwithrequired.raml
EmptyBase: !include emptybase.raml
Locale: !include locale.raml
NoProps: !include noprops.raml
ObjectAsMap: !include objectasmap.raml
ParentWithOption: !include parentwithoption.raml
SomeEnum: !include enum.raml
