package:
  type: string
  allowedTargets: TypeDeclaration
docs-uri:
  type: string
scala-type:
  type: string
asMap:
  type: object
  properties:
    key: string
    value: string
scala-array-type:
  type: string
scala-extends:
  type: string
scala-derive-json:
  type: boolean
key-base-discriminator:
  type: string

