#%RAML 1.0 DataType
(package): KeyBasedTypes
(docs-uri): "https://example.org/key-base-type"
displayName: KeyBasePrefixInt
type: KeyBaseDiscriminator
(scala-derive-json): true
(key-base-discriminator): prefix
properties:
  prefix:
    type: number
    format: int64