#%RAML 1.0 DataType
(package): Other
(docs-uri): "https://example.org/map-like"
displayName: MapLike
type: NoSealedBase
(asMap):
  key: string
  value: Long
discriminatorValue: "map-like"
properties:
  //:
    type: string
