NoDiscriminatorBase: !include nodiscriminatorbase.raml
NoDiscriminatorSub1: !include nodiscriminatorsub1.raml
NoDiscriminatorSub2: !include nodiscriminatorsub2.raml
BaseType: !include basetype.raml
IntermediateType: !include intermediate.raml
GrandchildType: !include grandchild.raml
DataType: !include datatype.raml
EmptyBase: !include emptybase.raml
NoProps: !include noprops.raml
NoSealedBase: !include nosealedbase.raml
OtherSub: !include othersub.raml
MapLike: !include maplike.raml
SomeEnum: !include enum.raml
DefaultProperty: !include defaultproperty.raml
ConstrainedString: !include constrainedstring.raml
ParentWithOption: !include parentwithoption.raml
DerivedWithRequired: !include derivedwithrequired.raml
KeyBaseDiscriminator: !include keybasediscriminator.raml
KeyBaseWildcard: !include keybasewildcard.raml
KeyBasePrefixString: !include keybaseprefixstring.raml
KeyBasePrefixInt: !include keybaseprefixint.raml

