NoDiscriminatorBase: !include nodiscriminatorbase.raml
NoDiscriminatorSub1: !include nodiscriminatorsub1.raml
NoDiscriminatorSub2: !include nodiscriminatorsub2.raml
BaseType: !include basetype.raml
DataType: !include datatype.raml
EmptyBase: !include emptybase.raml
NoProps: !include noprops.raml
NoSealedBase: !include nosealedbase.raml
OtherSub: !include othersub.raml
MapLike: !include maplike.raml