#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/data-type"
displayName: DataType
type: BaseType
discriminatorValue: data
properties:
  foo?:
    type: string
  customTypeProp:
    (scala-type): "scala.long.BigDecimal"
    type: number
  customArrayTypeProp:
    (scala-array-type): "Vector"
    type: array
    items:
      type: object
