#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/base-without-facets-type"
displayName: BaseWithoutFacetsType
type: object
discriminator: type
properties:
  type: string
  id:
    type: string
