#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/base-type"
displayName: BaseType
type: object
(scala-extends): "Any"
(scala-derive-json): true
discriminator: type
properties:
  type: string
  id:
    type: string
    pattern: ^[A-z0-9-.]+$
    minLength: 1
    maxLength: 10
  optionalCustomArrayTypeProp?:
    (scala-array-type): "Set"
    (scala-type): "scala.math.BigDecimal"
    type: array
    items:
      type: number
      minimum: 0.0
    minItems: 1
    maxItems: 100
    uniqueItems: true
