#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/base-with-facets-type"
displayName: BaseWithFacetsType
type: object
discriminator: type
properties:
  type: string
  id:
    type: string
    minLength: 8
    maxLength: 64
    pattern: ^[A-z0-9-]*$
  count:
    type: number
    format: int32
    minimum: 0
  atMost100:
    type: number
    maximum: 100.0
  stringArray:
    type: array
    minItems: 1
    maxItems: 5
    items:
      type: string
      pattern: "^[A-z0-9]+$"
      minLength: 2
      maxLength: 99
