#%RAML 1.0 DataType
(package): DataTypes
(docs-uri): "https://example.org/derived-with-required-id"
displayName: DerivedWithRequired
type: ParentWithOption
(scala-derive-json): true
properties:
  _id: string
